name: ci

on:
  push:
    branches:
      - main

env:
  CI: true
  APP_IMAGE_NAME: vadimkulishov/devops-for-programmers-project-74
  DATABASE_NAME: postgres
  DATABASE_USERNAME: postgres
  DATABASE_PASSWORD: postgres
  DATABASE_HOST: db

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.26.0/docker-compose-Linux-x86_64" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Run tests with Docker Compose
        run: make ci

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.production
          push: true
          tags: ${{ env.APP_IMAGE_NAME }}